import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { Provider } from "@/app/providers/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SBTZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          {/* <BlackHeader theme="black" /> */}
          {children}
          {/* <BlackFooter /> */}
        </body>
      </Provider>
    </html>
  );
}
